### ISSUE TITLE
Decode piped bmp

### ISSUE THREAD

**Issue by FallingSnow** [shaozilee/bmp-js#7]
I am piping a bmp from [fluent-ffmpeg](https://github.com/fluent-ffmpeg/node-fluent-ffmpeg) through a stream to bmp-js (to decode it) but I keep getting `Index out of range` errors. It still outputs a `bmpData` object with the correct width and height though.

Also, do you know how I would go about taking `bmpData.data` and displaying it on an html5 canvas?

Thank you.

**Comment by tkalliom** [comment]
I had a somewhat similar problem, which was due to lack of support for 24bpp input. Have you tried whether the `rgb` flag solves your problem?

**Comment by FallingSnow** [comment]
I solved my issue a while back, not sure what I did though.
