### ISSUE TITLE
NPM package: --use_strict mode

### ISSUE THREAD

**Issue by ytiurin** [shaozilee/bmp-js#8]
Hi man, thanks for the great lib!

I just wanted to ask when the `node --use_strict` mode will be supported?
If you use the latest version of this lib (0.0.1 on NPM), it throws and exception:
```
module.exports = encode = function(imgData, quality) {
                        ^
ReferenceError: encode is not defined
    at Object.<anonymous> (/home//node_modules/bmp-js/lib/encoder.js:75:25)
```
I saw that recent commit (https://github.com/shaozilee/bmp-js/commit/88cda18e1a733c055fa34ba1bc2cf180ee428eb6) resolves this bug, but NPM package hasn't yet been updated.

Is there going to be an NPM update solving this bug?

**Comment by shaozilee** [comment]
Hi @ytiurin ,sorry about that i forgot to publish on npmjs.org. U can update the latest now and it works very well in strict mode

**Comment by ytiurin** [comment]
@shaozilee Great! Thank you.
